version: '3'

services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    container_name: logstash
    image: logstash:8.8.1
    user: root #сменил дефолтного юзера на рута
    ports:
      - "9600:9600"
    volumes:
      - /home/vagrant/logstash.conf:/usr/share/logstash/config/logstash.conf
      - /home/vagrant/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /home/vagrant/output.txt:/usr/share/logstash/output.txt
      - ./nginxlog:/usr/share/logstash/nginx # данный волум прокидываю для трех контейнеров и хоста, чтобы актуальные логи могли считываться
    command: logstash -f /usr/share/logstash/config/logstash.conf # была добавлена команда, которая запускает логстэш используя проброшенный конфиг
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: kibana:7.17.9
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.9
    command: --strict.perms=false
    user: root
    volumes:
      - /home/vagrant/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginxlog:/usr/share/filebeat/nginx # данный волум прокидываю для трех контейнеров и хоста, чтобы актуальные логи могли считываться

  nginx:
    image: nginx:1.25
    ports:
      - 80:80
    volumes:
      - ./nginxlog:/var/log/nginx # данный волум прокидываю для трех контейнеров и хоста, чтобы актуальные логи могли считываться
    restart: always

volumes:
  elasticsearch-data:
    driver: local
